// --------------------------------------------------------------------------------------------------------------------
// <copyright file="CodeGenSandboxDummyFactory.cs" company="OBeautifulCode">
//   Copyright (c) OBeautifulCode 2018. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in OBeautifulCode.CodeGenSandbox.Test source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace OBeautifulCode.CodeGenSandbox.Test
{
    using global::System;

    using FakeItEasy;

    using OBeautifulCode.AutoFakeItEasy;

    /// <summary>
    /// A Dummy Factory for types in <see cref="OBeautifulCode.CodeGenSandbox"/>.
    /// </summary>
#if !OBeautifulCodeCodeGenSandboxSolution
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::System.CodeDom.Compiler.GeneratedCode("OBeautifulCode.CodeGenSandbox.Test", "See package version number")]
    internal
#else
    public
#endif
    class CodeGenSandboxDummyFactory : DefaultCodeGenSandboxDummyFactory
    {
        public CodeGenSandboxDummyFactory()
        {
            /* Add any overriding or custom registrations here. */
        }
    }
}